security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        # in_memory: { memory: ~ }
        db_provider:
            entity:
                class: App\Entity\User



    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            pattern:    ^/
            provider: db_provider
            form_login:
                login_path: login
                check_path: login

            logout:
              path: /logout
              target: /


    access_control:
       - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
       - { path: ^/user/actions, roles: IS_AUTHENTICATED_FULLY }
       - { path: ^/members, roles: IS_AUTHENTICATED_FULLY }


    encoders:
        App\Entity\User: bcrypt
